### ISSUE TITLE
Using forge-1.12.2-14.23.5.2854-installer.jar Causes Errors 

### ISSUE THREAD

**Issue by Gizmo0320** [MCUpdater/MCU-LegacyForgeLoader#1]
Build is not successful with Forge Version 2854 for 1.12.2

 Here is the link to what it shows
https://pastebin.com/XdFH46xQ

**Comment by smbarbour** [comment]
I see the issue:  The latest version of Forge for 1.12.2 uses the new installer codebase and not the legacy installer codebase.

Build 1.12.2-14.23.5.2838 is what the LegacyLoader was designed against.  I'll need to take some time to note when the change occurred and how to handle this in the MCUpdater codebase to choose between legacy and modern forge installers.

**Comment by Gizmo0320** [comment]
Is there a work around that you know of, I currently just need the 1.12.2 version to work

**Comment by smbarbour** [comment]
Fixed by https://github.com/MCUpdater/MCU-API/commit/52cdc2d5d62491f8e8fa612532dd36fd9be62aa7

Fix is live in production
